project:
  type: website
  output-dir: docs

website:
  title: "Vasco Brazão"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: https://vbrazao.github.io/blog/
        text: Blog

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

