project:
  type: website
  output-dir: docs

website:
  title: "Vasco Brazão"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://vbrazao.github.io/blog/
        text: Blog
      - href: portfolio.qmd
        text: Portfolio
      - href: publications.qmd
        text: Publications

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

