---
title: "Portfolio"
toc-location: left
---

Rather than give a complete history of my educational and professional journey (which [my LinkedIn profile](https://www.linkedin.com/in/vascobrazao/) summarizes adequately), this page highlights selected projects I've been involved in to show you the breadth and depth of my work over the years and give you a glimpse into the skills I've developed along the way.

The page is split into two sections for now, showing projects from most to least recent, from my current work as an applied statistician and my previous life as a behavioral science consultant. If you think I can help you, don't hesitate to contact me on any channel present around the website or through [my Upwork profile](https://www.upwork.com/freelancers/~010ee2f24d43313103).

## Freelance Applied Statistician

:::: column-margin
::: {.callout-note appearance="minimal"}
See more of my journey as a freelance statistician and find out what clients say about me at [my Upwork profile](https://www.upwork.com/freelancers/~010ee2f24d43313103).
:::
::::

I was a Top Rated freelancer with 100% Job Success on Upwork. I also consulted for clients outside of the platform.

### Researching intimate partner violence with complex survey data

Most recently, I've been working with a sociologist on analyses related to intimate partner violence, seeking to apply an intersectional lens to understanding how race and gender interact to predict this phenomenon. Because we are using data from a complex survey, I've had to delve into the world of survey-weighted analyses. This work has not been published yet, but I’ve written up a [post documenting some specific challenges I found during analyses and how I resolved them](https://vbrazao.github.io/blog/posts/2023-12-21_mediation-weighted-glm/) which can give you a glimpse into my technical and problem-solving skills.

## Behavioral Scientist at CLOO - Behavioral Insights Unit

### Reducing food waste by 24% in company canteens with behavioral interventions

:::: column-margin
::: {.callout-note appearance="minimal"}
Read more about this project at the [BRF Hub Blog](https://www.hubbrf.com/blog/cases-de-sucesso/brf-reduz-24-do-desperdicio-alimentar-diario-em-seus-restaurantes/) (page in Portuguese — use an automatic translator if required; [archived link](https://web.archive.org/web/20240520112712/https://www.hubbrf.com/blog/cases-de-sucesso/brf-reduz-24-do-desperdicio-alimentar-diario-em-seus-restaurantes/)).
:::
::::

In 2021, I was part of the core team working to reduce food waste at the worker canteens of BRF — a Brazillian food processing company and one of the largest such companies in the world. Our interventions reduced daily food waste by an average of 24% at three sites. To achieve this, we conducted diagnostics in loco, developed behavioral interventions, measured our impact against control canteens, and ensured our interventions did not negatively impact the workers by running surveys before and after the implementation, always working closely with the team at BRF.

My role involved developing the methodological strategy, defining and coordinating the measurement strategy, delivering weekly reports to the BRF team on our ongoing measurements, conducting exploratory and inferential analyses of the daily food waste data as well as the survey data, and drafting parts of the final report and presentation.

### Leading scientific support work for an applied research project

In 2020/2021, I led our work supporting the [SUSTAINMEALS](https://www.sustainmeals.org/projeto?lang=en) project. Coordinated by João Graça, PhD, the project sought to increase knowledge and generate evidence with the ultimate goal of facilitating a large-scale shift towards healthier and more sustainable plant-based meals throughout Portugal. I was responsible for leading CLOO’s team within the project, focusing on three key outputs:

-   We helped to improve a behavioral change [Toolkit](https://www.sustainmeals.org/toolkit?lang=en) that documented and explained 27 behavioral change techniques that can be used to increase consumers’ adoption of healthier or more sustainable meal choices in collective meal contexts and included an implementation guide and corresponding worksheets as well as a diagnostic to facilitate the independent application of these techniques by relevant stakeholders. Our team worked closely with the SUSTAINMEALS team on all aspects of the toolkit, but our biggest contribution may have been finding and explaining concrete, published examples of each behavioral change technique in order to bring readers closer to the research base for the toolkit and illustrate each technique so readers may better understand and eventually apply it.

-   I contributed towards a [systematic scoping review published in Appetite](https://www.sciencedirect.com/science/article/pii/S0195666323001502) that “aimed to map determinants of dietary change in collective meal contexts across multiple settings, interventions, target groups, and target behaviors.” While most of the work was carried out by the project team, I earned authorship credit by helping to develop a scoring system for open science indicators and conducting the data extraction for those indicators, drafting the relevant sections of the manuscript, and reviewing the manuscript as it approached its final version.

-   My most challenging contribution was leading the methodological work, technical implementation, and statistical analysis of a [field experiment published in Public Health Nutrition](https://www.cambridge.org/core/journals/public-health-nutrition/article/promoting-plantbased-eating-in-meatcentric-meal-contexts-a-field-study/92B765BD49ABBED76C7498AB7984A7B0). Together with a team from CLOO and SUSTAINMEALS, we developed an intervention to increase the proportion of plant-based meals sold at a university canteen in the Lisbon area. This required coordinating with our partners at the university, from the highest levels of management to the canteen workers who helped us improve menu descriptions and ensure that the data we required was adequately recorded. We did our best to follow open science practices and placed all [code and materials in a public online repository](https://osf.io/nuhkv/).

### Leading a cluster-randomized evaluation of an EdTech app

:::: column-margin
::: {.callout-note appearance="minimal"}
To learn more about this work, read the [final report we submitted as the final milestone for the Solving Together Fund](https://res.cloudinary.com/upwork-fp/image/upload/v1674465028/profile/portfolio/778625175288537088/a63k7fwmslupqlxjrzsh.pdf).
:::
::::

In 2019/2020, I led the methodological and analysis tasks of a project for the first time. We supported Eedi, an EdTech company who develop a formative assessment educational app used in schools throughout the United Kingdom, to test the impact of granting parents access to the app on pupils’ educational and app-related outcomes. This work, supported by [Nesta’s Solving Together Fund](https://www.nesta.org.uk/blog/solving-together-helping-parents-to-support-their-childs-maths-education/), involved designing and conducting a cluster-randomized trial to test the parent roll-out in 79 Year 7 and 8 classes in 9 schools. While our intervention did not produce the intended outcomes, the process was a rich learning experience for myself and for Eedi — for example, my exploratory data analysis made it clear to the Eedi team that pupil outcomes were much more dependent on the teacher rather than the parents or even app features, as we showed that certain teachers managed to produce high levels of engagement with the app regardless of which year they taught, whereas others seemed to always display poor engagement.

Besides working to develop the interventions and describing research that would increase Eedi’s knowledge of how to generate positive engagement with their products, my biggest learning experience was enabled by the design of the study itself: clustered data for educational interventions need to be analyzed with a statistical model that adequately accounts for the clustering. I had the chance to autonomously learn about, apply, and interpret multi-level generalized linear models, and have kept refining my skills in this area ever since.
